[package]
name = "clirus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr = "0.22"
tungstenite = { version = "0.19", features = ["rustls-tls-webpki-roots"]}

nostr-sdk-net = "0.22.0"